--2.BAYÝLERÝN 0 STOÐA SAHÝP ÜRÜNLERÝN GETÝREN FONK.

CREATE FUNCTION DEALER_0_STOCK_PIECE()
RETURNS TABLE 
AS
RETURN
SELECT DEALERID,DEALERNAME, PRODUCTCODE,PRODUCTNAME, STOCKPIECE FROM COMPANY_PRODUCTDEALER PD
INNER JOIN PRODUCT_PRODUCT P ON P.PRODUCTID=PD.PRODUCTID
INNER JOIN COMPANY_DEALERS D ON D.ID=PD.DEALERID
WHERE STOCKPIECE=0

SELECT * FROM DBO.DEALER_0_STOCK_PIECE()