--1.ÇALIÞAN NUMARASI GÝRÝLEN ÇALIÞANIN SATMIÞ OLDUÐU ÜRÜNLERÝ VE SATIÞ TARÝHÝNÝ GETÝREN FONK.

CREATE FUNCTION EMPLOYEE_SALES (@EMPLOYEEID INT)
RETURNS TABLE
AS
RETURN
SELECT E.EMPLOYEEID,FIRSTNAME,LASTNAME,PRODUCTNAME,SD.DATE_
FROM SALES_EMPLOYEES E
INNER JOIN SALES_SALES S ON S.EMPLOYEEID=E.ID
INNER JOIN SALES_SALESDETAILS SD ON SD.PRODUCTID=S.PRODUCTID
INNER JOIN PRODUCT_PRODUCT P ON P.PRODUCTID=SD.PRODUCTID
WHERE E.EMPLOYEEID=@EMPLOYEEID
GROUP BY E.EMPLOYEEID,FIRSTNAME,LASTNAME,PRODUCTNAME,SD.DATE_

SELECT * FROM dbo.EMPLOYEE_SALES(5)