--4.ÜRÜN KATEGORÝSÝ 1 OLAN ÜRÜN ÝÇÝN  BAYÝ BAZLI STOK ADETLERÝNÝ VÝEW

CREATE VIEW PRODUCTCODE_1_STOCK
AS
SELECT PRODUCTNAME,PRODUCTCODE, DEALERID, 
SUM(STOCKPIECE) AS TOTAL_STOCK
FROM PRODUCT_PRODUCT P
INNER JOIN PRODUCT_PRODUCTCATEGORIES PC ON PC.ID=P.CATEGORYID
INNER JOIN PRODUCT_PRODUCTSUBCATEGORIES PSC ON PSC.CATEGORYID=PC.ID
INNER JOIN COMPANY_PRODUCTDEALER PD ON PD.PRODUCTID=P.PRODUCTID
WHERE PSC.CATEGORYID=1
GROUP BY PRODUCTCODE, DEALERID,PRODUCTNAME