--1.BAYÝLERÝN SON 3 YILLIK SATIÞ TUTARINI GETÝREN VÝEW

CREATE VIEW TOTAL_ANNUAL_SALES
AS
SELECT YEAR(SD.DATE_) AS YEAR, 
SUM(UNITPRICE) AS TOTAL_SALES
FROM COMPANY_DEALERS D
INNER JOIN COMPANY_PRODUCTDEALER PD ON PD.DEALERID=D.ID
INNER JOIN SALES_SALESDETAILS SD ON SD.PRODUCTID=PD.PRODUCTID
WHERE SD.DATE_='2017'
GROUP BY DATE_
UNION 
SELECT YEAR(SD.DATE_), SUM(UNITPRICE) FROM COMPANY_DEALERS D
INNER JOIN COMPANY_PRODUCTDEALER PD ON PD.DEALERID=D.ID
INNER JOIN SALES_SALESDETAILS SD ON SD.PRODUCTID=PD.PRODUCTID
WHERE SD.DATE_='2018'
GROUP BY DATE_
UNION
SELECT YEAR(SD.DATE_), SUM(UNITPRICE) FROM COMPANY_DEALERS D
INNER JOIN COMPANY_PRODUCTDEALER PD ON PD.DEALERID=D.ID
INNER JOIN SALES_SALESDETAILS SD ON SD.PRODUCTID=PD.PRODUCTID
WHERE SD.DATE_='2019'
GROUP BY DATE_