--5.BAYÝ ÇALIÞANLARININ 2019 YILINDA YAPTIKLARI SATIÞ TUTARLARINI GETÝREN VÝEW

CREATE VIEW DEALER_EMPLOYEE_SALES_2019
AS
SELECT  S.EMPLOYEEID, FIRSTNAME,LASTNAME,
SUM(UNITPRICE)  AS TOTALPRICE
FROM SALES_SALES S
INNER JOIN SALES_SALESDETAILS SD ON SD.PRODUCTID=S.PRODUCTID
INNER JOIN SALES_CUSTOMERS C ON C.ID=S.EMPLOYEEID
WHERE YEAR(S.DATE_)=2019
GROUP BY EMPLOYEEID, FIRSTNAME,LASTNAME 