--2.KÜÇÜK EV ALETLERÝNÝN STOK SAYILARINI GETÝREN VÝEW:

CREATE VIEW SMALL_HOME_APPLIANCES_STOCK
AS
SELECT DEALERID, PRODUCTNAME,PRODUCTCODE, SUM(STOCKPIECE) AS STOCK 
FROM PRODUCT_PRODUCTCATEGORIES PC 
INNER JOIN PRODUCT_PRODUCT P ON P.CATEGORYID=PC.ID
INNER JOIN COMPANY_PRODUCTDEALER PD ON PD.PRODUCTID=P.PRODUCTID
WHERE PC.ID IN (7,8,9,10,11,12)
GROUP BY PRODUCTNAME,DEALERID,PRODUCTCODE