--1.ÜRÜN KODU GÝRÝLEN ÜRÜNÜN TOPLAM SATIÞ MÝKTARI PROSEDÜRÜ
CREATE PROCEDURE SP_TOTAL_SALES_QUANTITY
@PRODUCTCODE NVARCHAR(20)
AS
SELECT PRODUCTNAME,SUM(QUANTITY) AS TOTAL_SALES_QUANTITY 
FROM PRODUCT_PRODUCT P 
INNER JOIN SALES_SALESDETAILS SD ON SD.PRODUCTID=P.PRODUCTID
WHERE PRODUCTCODE=@PRODUCTCODE
GROUP BY PRODUCTNAME

EXEC SP_TOTAL_SALES_QUANTITY @PRODUCTCODE='KDN28NW20N'