--2.GÝRÝLEN MÜÞTERÝ ID YE GÖRE ALINAN ÜRÜN VE BAYÝ ÝSMÝNÝ GETÝREN PROC
CREATE PROCEDURE SP_CUS_PRODUC_DEALER_INFORMATION
@CUSTOMERID INT
AS
SELECT CUSTOMERID, FIRSTNAME,LASTNAME, PRODUCTNAME, PRODUCTCODE, DEALERNAME, DATE_  FROM SALES_SALES S 
INNER JOIN COMPANY_PRODUCTDEALER PD ON PD.PRODUCTID=S.PRODUCTID
INNER JOIN COMPANY_DEALERS D ON D.ID=PD.DEALERID
INNER JOIN SALES_CUSTOMERS C ON C.ID=S.CUSTOMERID
INNER JOIN PRODUCT_PRODUCT P ON P.PRODUCTID=PD.PRODUCTID
WHERE CUSTOMERID=@CUSTOMERID

EXEC SP_CUS_PRODUC_DEALER_INFORMATION @CUSTOMERID='24'