--3.YETKÝLÝ SERVÝSID SÝ GÝRÝLEN SERVÝSÝN YAPTIÐI ÝÞLEM TÜRÜ, ÜRÜN KODU,ÝÞLEM YAPTIÐI MÜÞTERÝ BÝLGÝSÝ PROC
CREATE PROCEDURE SP_SERVICE_CUSTOMER_DETAIL
@EMPLOYEEID INT
AS
SELECT ASD.EMPLOYEEID, E.FIRSTNAME,E.LASTNAME, PRODUCTCODE,SERVICE_,C.FIRSTNAME AS CUSTOMERNAME,
C.LASTNAME AS CUSTOMERLASTNAME FROM COMPANY_AUTHORIZEDSERVICEDETAILS ASD 
INNER JOIN SALES_CUSTOMERS C ON C.ID=ASD.CUSTOMERID
INNER JOIN PRODUCT_PRODUCT P ON P.PRODUCTID=ASD.PRODUCTID
INNER JOIN SALES_EMPLOYEES E ON E.EMPLOYEEID=ASD.EMPLOYEEID
WHERE E.EMPLOYEEID=@EMPLOYEEID

EXEC SP_SERVICE_CUSTOMER_DETAIL @EMPLOYEEID='1'