--5.KAMPANYADAKÝ ÜRÜNLERÝN SATIÞ MÝKTARINI VE STOK ADETLERÝNÝ GETÝREN PROC
CREATE PROCEDURE SP_CAMPAING_SALES_STOCK_QUANTITY
@PRODUCTCODE NVARCHAR (20)
AS
SELECT PRODUCTCODE,PRODUCTNAME, 
SUM(QUANTITY) AS TOTAL_QUANTITY,
SUM(STOCKPIECE) AS TOTALSTOCK
FROM COMPANY_CAMPAIGN C
LEFT JOIN COMPANY_PRODUCTDEALER PD ON PD.PRODUCTID=C.PRODUCTID
INNER JOIN PRODUCT_PRODUCT P ON P.PRODUCTID=PD.PRODUCTID
INNER JOIN SALES_SALESDETAILS SD ON SD.PRODUCTID=C.PRODUCTID
WHERE PRODUCTCODE= @PRODUCTCODE
GROUP BY PRODUCTCODE,PRODUCTNAME

EXEC SP_CAMPAING_SALES_STOCK_QUANTITY @PRODUCTCODE='KGN76AIF0N'